"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""
"" Ondruv megazazracnysuperhyperultrasuprafreecoolinkonfigurag 
""
"" Copyright (c) Ondra
""
"" Tento konfigurak byl zplagiatorovan Gaussem
""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" Gone to emacs
""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
